### ISSUE TITLE
Remove proxy

### ISSUE THREAD

**Issue by friedger** [REBL-Stack/starter-app#7]
Using proxy is evil, at least a little bit. The starter-app should be self-contained so that it runs without infrastructure or knowledge on the server.

**Comment by njordhov** [comment]
I partly agree with you... at least for this special case. Let's hash it out on the principles in a more public fora though, like at the [NIL CBE issue tracker](https://github.com/newinternetlabs/new-internet-extension/issues).

**Comment by friedger** [comment]
Continuing this one at https://github.com/newinternetlabs/new-internet-extension/issues/23
